// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3L7oWrrAZPxn6cAGGUfTIoNUe8__rzUA',
    appId: '1:96899027797:web:29ce119505db85a09d15dc',
    messagingSenderId: '96899027797',
    projectId: 'canderm-ac3bb',
    authDomain: 'canderm-ac3bb.firebaseapp.com',
    storageBucket: 'canderm-ac3bb.firebasestorage.app',
    measurementId: 'G-J6T6HJP5ZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0KwEZlhrPUdHJksMspKlsqFXgLDygU9g',
    appId: '1:96899027797:android:6e406772e4353bfe9d15dc',
    messagingSenderId: '96899027797',
    projectId: 'canderm-ac3bb',
    storageBucket: 'canderm-ac3bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBosyIGIQg4Qc8Uc-O2OcuXyn1TUmuEBho',
    appId: '1:96899027797:ios:9282b14cd3e1a92e9d15dc',
    messagingSenderId: '96899027797',
    projectId: 'canderm-ac3bb',
    storageBucket: 'canderm-ac3bb.firebasestorage.app',
    iosBundleId: 'com.example.canderm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBosyIGIQg4Qc8Uc-O2OcuXyn1TUmuEBho',
    appId: '1:96899027797:ios:9282b14cd3e1a92e9d15dc',
    messagingSenderId: '96899027797',
    projectId: 'canderm-ac3bb',
    storageBucket: 'canderm-ac3bb.firebasestorage.app',
    iosBundleId: 'com.example.canderm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3L7oWrrAZPxn6cAGGUfTIoNUe8__rzUA',
    appId: '1:96899027797:web:42ef787d4ce6fd5b9d15dc',
    messagingSenderId: '96899027797',
    projectId: 'canderm-ac3bb',
    authDomain: 'canderm-ac3bb.firebaseapp.com',
    storageBucket: 'canderm-ac3bb.firebasestorage.app',
    measurementId: 'G-J2YPHK632D',
  );
}
